import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Image from "next/image";
import { Utensils } from "lucide-react";
import { getSpecials } from "@/lib/actions";
import AddToCartButton from "@/components/AddToCartButton";

export type Special = {
    name: string;
    description: string;
    price: string;
    originalPrice: string;
    imageUrl: string;
    imageHint: string;
    tag: string;
};

export default async function SpecialsPage() {
    const specials = await getSpecials();

    return (
        <div className="container mx-auto px-4 py-12 md:py-24">
            <div className="text-center mb-12">
                <div className="inline-block bg-primary/10 text-primary p-3 rounded-full mb-4">
                    <Utensils className="h-8 w-8" />
                </div>
                <h1 className="text-4xl md:text-5xl font-headline font-bold">Daily Specials</h1>
                <p className="mt-4 text-lg text-muted-foreground">Amazing deals on your favorite dishes, generated by AI and available for a limited time!</p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {specials.map((special) => (
                    <Card key={special.name} className="flex flex-col overflow-hidden transition-transform duration-300 hover:scale-105 hover:shadow-xl">
                        <CardHeader className="p-0 relative">
                            <Badge className="absolute top-2 right-2">{special.tag}</Badge>
                            <div className="aspect-video relative">
                                <Image
                                    src={special.imageUrl}
                                    alt={special.name}
                                    data-ai-hint={special.imageHint}
                                    fill
                                    className="object-cover"
                                />
                            </div>
                        </CardHeader>
                        <CardContent className="flex-grow p-6">
                            <CardTitle className="font-headline text-2xl mb-2">{special.name}</CardTitle>
                            <CardDescription>{special.description}</CardDescription>
                        </CardContent>
                        <div className="flex justify-between items-center p-6 pt-0">
                            <div className="flex items-baseline gap-2">
                                <p className="text-2xl font-bold text-primary">${special.price}</p>
                                <p className="text-md font-medium text-muted-foreground line-through">${special.originalPrice}</p>
                            </div>
                            <AddToCartButton name={special.name} price={special.price} imageUrl={special.imageUrl} imageHint={special.imageHint} />
                        </div>
                    </Card>
                ))}
            </div>
        </div>
    );
}
